### ISSUE TITLE
MBar for pressure and windspeed for windspeed

### ISSUE THREAD

**Issue by domowarrior** [briis/hass-weatherflow#17]
Hi Briis ,
excellent follow up to your last version.
I have a tempest system bye the way.

one issues : 

How do i get the pressure in mb
which i get in my weatherflow app.

I now get pressure in  hPa

**Comment by briis** [comment]
> How do i get the pressure in mb

Mb and hPa are the same values, so this is just about the Unit that is displayed not the actual value. I had to pick one, and I picked hPa. In the UI, you can often overwrite the Unit displayed.

Are you seeing a difference in the actual number displayed for pressure, or is it just the unit behind it?

**Comment by briis** [comment]
The unit you see in the Tempest App, is set by you when you in the App. You have selected MBar and others have selected hPa. The value for both these units is the same, it is just the unit type that differs. 

In most of the Lovelace cards, where you would display this, you can specify the unit, so that you would display Mbar instead of hPa.

So this will not be fixed for now. I might consider in a future release to give the option of specifying the Display unit, but this is bigger change than it sounds like.

Closing this issue.
