### ISSUE TITLE
Error occured processing forecast data. Error message: 'icon'

### ISSUE THREAD

**Issue by slbailey** [briis/hass-weatherflow#28]
I have started receiving this error today:

Retrying setup: Error while retreiving forecast data: Error occured processing forecast data. Error message: 'icon'

**Comment by briis** [comment]
Check your hub and device. This is normally caused by the HW not sending data to WeatherFlow

**Comment by slbailey** [comment]
https://tempestwx.com/station/34094/grid

Seems to be sending data to weatherflow.

**Comment by briis** [comment]
I will check the raw data

**Comment by briis** [comment]
It turned out I had already fixed that issue, just never released it 😁
On rare occasions WeatherFlow is not adding anything to the `icon` field, and the program did not like that - now if this happens, I will set the icon to *Cloudy*, so that we can continue. It normally updates again after some time. I might find a better Icon/State later, but this will fix your error. Look out for V1.0.3 in HACS.
